name: parkdayfinder
description: "parkdayfinder is a comprehensive and intuitive mobile application designed to streamline the allocation and management of parking bays for organizations, teams, and communities. Say goodbye to the hassle of manual scheduling and ensure everyone has a designated parking spot with ease. Made with Flutter"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  english_words: any
  provider: ^6.0.0
  intl: ^0.19.0
  lottie: ^3.1.2
  firebase_core: ^3.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/schedule.json
    - assets/cam.png
    - assets/leah.png
    - assets/jeffry.png
    - assets/kieran.png
    - assets/stratton.png
    - assets/frans.png
    - assets/adam_m.png
    - assets/michelle.png
    - assets/underconstruction.json
