name: parkdayfinder
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  english_words: any
  provider: ^6.0.0
  intl: ^0.17.0
  lottie: ^1.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/schedule.json
    - assets/cam.png
    - assets/leah.png
    - assets/jeffry.png
    - assets/kieran.png
    - assets/stratton.png
    - assets/frans.png
    - assets/adam_m.png
    - assets/michelle.png
    - assets/underconstruction.json
