// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy8K75GoC3KmnNra-AnC4c0JUqZ_EyIQw',
    appId: '1:490409550066:web:ee3e38ab1222ca9c65f06b',
    messagingSenderId: '490409550066',
    projectId: 'park-day-finder',
    authDomain: 'park-day-finder.firebaseapp.com',
    storageBucket: 'park-day-finder.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8pVLGipmVnukt1KDN0fSxnr0OmPZZqLU',
    appId: '1:490409550066:android:fa0a95564ab6ada565f06b',
    messagingSenderId: '490409550066',
    projectId: 'park-day-finder',
    storageBucket: 'park-day-finder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfu6eKVSGB6BVJOeri6eSuWXf-xHVh-TY',
    appId: '1:490409550066:ios:a287acc0d4b4249d65f06b',
    messagingSenderId: '490409550066',
    projectId: 'park-day-finder',
    storageBucket: 'park-day-finder.appspot.com',
    iosBundleId: 'alue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfu6eKVSGB6BVJOeri6eSuWXf-xHVh-TY',
    appId: '1:490409550066:ios:bed8337eeb89a7da65f06b',
    messagingSenderId: '490409550066',
    projectId: 'park-day-finder',
    storageBucket: 'park-day-finder.appspot.com',
    iosBundleId: 'com.gigabyting.parkdayfinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy8K75GoC3KmnNra-AnC4c0JUqZ_EyIQw',
    appId: '1:490409550066:web:cb7f90af330bf20665f06b',
    messagingSenderId: '490409550066',
    projectId: 'park-day-finder',
    authDomain: 'park-day-finder.firebaseapp.com',
    storageBucket: 'park-day-finder.appspot.com',
  );
}
