name: Build Mobile Apps

on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: macos-latest # macOS runner is required for iOS builds
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x" # Specify your Flutter version
          channel: "stable" # or 'beta', depending on your needs

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release

      - name: Build iOS (no codesigning)
        run: flutter build ios --release --no-codesign

      - name: Upload Android Build
        uses: actions/upload-artifact@v2
        with:
          name: android-release
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload iOS Build
        uses: actions/upload-artifact@v2
        with:
          name: ios-release
          path: build/ios/iphoneos/Runner.app

      - name: Archive Android and iOS Builds
        run: |
          mkdir -p releases
          cp build/app/outputs/flutter-apk/app-release.apk releases/
          zip -r releases/ios-release.zip build/ios/iphoneos/Runner.app

      - name: Upload Archived Builds
        uses: actions/upload-artifact@v2
        with:
          name: mobile-releases
          path: releases/
